[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.33.0"
ci = "github"
installers = ["homebrew"]
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
]
pr-run-mode = "upload"
hosting = "github"
checksum = "sha256"
github-attestations = false
install-updater = false
tap = "choplin/homebrew-tap"
formula = "revia"
publish-jobs = ["homebrew"]

[dist.github-action-commits]
"actions/checkout" = "d23441a48e516b6c34aea4fa41551a30e30af803"
"actions/upload-artifact" = "043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"
"actions/download-artifact" = "3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"
"swatinem/rust-cache" = "6323deb102c322ba6fcbdcafc7e3dddab59af2b6"
